kernel/builder: Remove dangling symlink
Fixes the following error when compiling a kernel with the latest Nixpkgs:
```
ERROR: noBrokenSymlinks: the symlink /nix/store/3a842gfl010rpfvr8mh2agig04pmbjvv-linux-6.13.8/lib/modules/6.13.8/build points to /build directory: /build/source/build
ERROR: noBrokenSymlinks: found 1 dangling symlinks, 0 reflexive symlinks and 0 unreadable symlinks
```

Edited by @samueldr to (1) use `rm -f` to prevent breakage when the
symlink does not exist, and (2) add an additional broken symlink to
remove (reported by FooSensei).

Co-authored-by: FooSensei <masterfoo@nym.hush.com>
Co-authored-by: Samuel Dionne-Riel <samuel@dionne-riel.com>